using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using Npgsql;
using System.Data;
using System.Windows.Controls.Primitives;


namespace PreformWPF
{
    /// <summary>
    /// Логика взаимодействия для Page2.xaml
    /// </summary>
    public partial class Page2 : Page
    {
        public Page2()
        {
            InitializeComponent();
            con.ConnectionString = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString.ToString();
        }

        private void btn_Add_Click(object sender, RoutedEventArgs e)
        {
            AddShipping addsh = new AddShipping();
            addsh.Show();
        }

        private void dgShipping_RowEditEnding(object sender, DataGridRowEditEndingEventArgs e)
        {

        }

        private void dgShipping_BeginningEdit(object sender, DataGridBeginningEditEventArgs e)
        {

        }

        NpgsqlConnection con = new NpgsqlConnection();

        private void LoadTable_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                con.Open();
                string querystring = "select id_shipping, status, ka_name, ka_city, shipping_date, paying_date, manager from shippings";
                NpgsqlCommand cmd = new NpgsqlCommand(querystring, con);
                cmd.ExecuteNonQuery();

                NpgsqlDataAdapter adapter = new NpgsqlDataAdapter(cmd);
                DataTable dt = new DataTable("shippings");
                adapter.Fill(dt);
                dgShipping.ItemsSource = dt.DefaultView;

                con.Close();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
        }

        //public void dgShipping_AutoGeneratedColumns(object sender, DataGridColumnHeader e)
        //{
        //    dgShipping.Columns[0].Header = "ID";
        //    dgShipping.Columns[1].Header = "Контрагент";
        //    dgShipping.Columns[2].Header = "Город";
        //    dgShipping.Columns[3].Header = "Дата отправления";
        //    dgShipping.Columns[4].Header = "Дата оплаты";
        //    dgShipping.Columns[5].Header = "Менеджер";
        //}

        private void btn_Add_Click_1(object sender, RoutedEventArgs e)
        {
            AddShipping AddSh = new AddShipping();
            AddSh.Show();
        }

        private void btn_Edit_Click(object sender, RoutedEventArgs e)
        {

        }

        private void btn_Delete_Click(object sender, RoutedEventArgs e)
        {

        }


    }
}
